# Generated by Django 2.2.16 on 2022-08-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220814_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='rate',
            new_name='rating',
        ),
    ]
